
FROM python:3.10-slim


WORKDIR /deployment


COPY requirements.txt /deployment/


RUN pip install --upgrade pip


RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir localstack-client boto3


COPY . /deployment/


EXPOSE 9696


ENTRYPOINT ["gunicorn", "--bind=0.0.0.0:9696", "app:app"]
